spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynotes
    username: user
    password: pass
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
